### PR TITLE
Big changes, tests added

### PR DESCRIPTION
**Pull request by jscissr**
Now, http-parser-js supports many more things like upgrade requests (websockets), keep-alive, trailers, header size limit, etc.
I also added tests from node and mscdex/io.js (#6).
You just have to update the version and `npm publish`.

### CODE REVIEW

**Comment by jscissr** [comment]
And by the way, my benchmark results (Win 7, node 0.12.3, `tests/bench-realworld.js`):
```
http_parser.c: 2402 req/s
old http-parser-js: 2240 req/s
jscissr/http-parser-js: 2349 req/s
```
So it's nearly as fast as `http_parser.c` :smiley:

**Comment by Jimbly** [comment]
Great work!

However, some tests seem to be failing for me, and then it hangs:
```
$ node --version
v0.10.25
$ git pull git://github.com/jscissr/http-parser-js.git tests
$ npm test

> http-parser-js@0.2.3 test /Users/jimb/http-parser-js
> python tests/test.py && node tests/iojs/test-http-parser-durability.js

=== release test-http-abort-queued ===
Path: simple/test-http-abort-queued
listen 64522
Got res: 200
{ date: 'Tue, 26 May 2015 16:29:59 GMT',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked' }
Read 3 bytes
 chunk="foo"
Response ended.
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "/thatotherone" == "/"
    at Server.<anonymous> (/Users/jimb/http-parser-js/tests/simple/test-http-abort-queued.js:30:10)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)
Command: node /Users/jimb/http-parser-js/tests/simple/test-http-abort-queued.js
=== release test-http-agent-destroyed-socket ===
Path: simple/test-http-agent-destroyed-socket
/Users/jimb/http-parser-js/tests/simple/test-http-agent-destroyed-socket.js:46
  var key = agent.getName(requestOptions);
                  ^
TypeError: Object #<Agent> has no method 'getName'
    at ClientRequest.<anonymous> (/Users/jimb/http-parser-js/tests/simple/test-http-agent-destroyed-socket.js:46:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:525:27)
Command: node /Users/jimb/http-parser-js/tests/simple/test-http-agent-destroyed-socket.js
=== release test-http-agent-keepalive ===
Path: simple/test-http-agent-keepalive
module.js:340
    throw err;
          ^
Error: Cannot find module '_http_agent'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jimb/http-parser-js/tests/simple/test-http-agent-keepalive.js:25:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
Command: node /Users/jimb/http-parser-js/tests/simple/test-http-agent-keepalive.js
[00:02|%  15|+  18|-   3]: release test-http-client-abort
```

**Comment by jscissr** [comment]
Well, the tests are from node 0.12.3, so they won't work for the old version. But if you still want to support 0.10.x and have separate tests for it, you could do this.

**Comment by Jimbly** [comment]
I definitely still need to support 0.10.x for the module itself (I'm relying on it in production and our company's distribution of node won't be bumping up to 0.12 until they're sure it's stable enough, which might be a while).  It's probably fine if the tests only run on 0.12 though.  I'll try using your branch and make sure things still work in our environment on 0.10.

**Comment by jscissr** [comment]
Basically, you could simply take the github repo of node 0.10 and add this line to `test/common.js`:
```js
process.binding('http_parser').HTTPParser = require('/path/to/http-parser.js').HTTPParser;
```
and start the tests from the commandline:
```
python tools/test.py
```
I only had to modify 2 tests because they expected earlier failing on invalid input.

**Comment by jscissr** [comment]
Just realized that I left this line commented out :flushed:. But the tests still pass after fixing it.

**Comment by Jimbly** [comment]
The test-http-parser-durability runs fine on node 0.10, and everything passes, and I had no problems running this in my particular app on node 0.10, so I think it's just the other tests that aren't compatible, which I think is fine.  I've added a couple test cases (specifically, some malformed headers which the Node native parser choked on, which is the reason I started using this module), trimmed the "old status" stuff from the README, and bumped the version number to 0.3.0.

**Comment by Jimbly** [comment]
An update: I've been unable to publish these changes to npm so far.  I filed [a bug](https://github.com/npm/npm/issues/8367) with npm, but have not received a response yet.  I can publish all of my other modules fine, so the only thing I can think of is either a) npm registry is busted for this module or b) the fact that I am not the original author/owner of this module is causing problems (I've published this module before without problems though, so I'm not sure why that would be an issue just now).  @creationix , can you try publishing this module (just grab what's in master and do an `npm publish`), and let me know if you also get a 404? That would narrow down the possibilities of what is the problem, and possibly get these changes live.

**Comment by creationix** [comment]
Seemed to work:

```
Timothys-MBP:http-parser-js tim$ npm publish
+ http-parser-js@0.3.0
```

Btw, great work both of you!

**Comment by Jimbly** [comment]
Thanks, good to know it's published, I'll double check everything on my side and update the NPM issue with this info.

**Comment by Jimbly** [comment]
Actually, on this page: https://www.npmjs.com/package/http-parser-js/access it looks like you are the only one who currently has access to publish to npm, perhaps I got removed somehow?

**Comment by creationix** [comment]
@Jimbly yep, something is wrong in npm land.  What's your npm username?  I'll add you again through the website.

**Comment by Jimbly** [comment]
@creationix My user name is Jimbly (https://www.npmjs.com/~Jimbly).  Thanks.

**Comment by creationix** [comment]
Oh interesting, the `J` must be capital.  I wonder if that's part of the problem.

**Comment by Jimbly** [comment]
Perhaps!  Looks good now (now I get "0.3.0 already exists" instead of "404 not found", so I'm guessing it's fixed).  I'll update the NPM issue with this info (problem is probably just that the error message is wrong/confusing, although I'll mention the case issue, maybe you added me as "jimbly" before and something changed...).
